version: '3'

services:
  web:
    build: ./python3.6
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/usr/src/app
    ports:
      - 8002:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
    networks:
      - default
  db:
    image: mariadb:10.3
    ports: 
      - "3306"
    environment:
      MYSQL_DATABASE: sample
      MYSQL_USER: user123
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
    networks:
      - default
